package habit.tracker.hciconz

object HCIconUtils {
    enum class IconCategory(val id: String, val displayName: String) {
        ART("art", "Art"),
        PRODUCTIVITY("work", "Work"),
        NATURE("personal", "Personal"),
        HEALTH("health", "Health"),
        SOCIAL("fitness", "Fitness"),
        TRENDING("trending", "Trending"),
    }

    private val iconsByCategory: Map<IconCategory, List<HCImageVector>> by lazy {
        mapOf(
            IconCategory.ART to listOf(
                HCImageVector(
                    "palette",
                    "Palette",
                    "Art,Painting,Colors,Brush,Design",
                    "art",
                    "Art",
                    R.drawable.hc_ic_palette
                ),
                HCImageVector(
                    "chef_hat",
                    "Chef Hat",
                    "Cooking,Kitchen,Chef,Culinary,Baking",
                    "art",
                    "Art",
                    R.drawable.hc_ic_chef_hat
                ),
                HCImageVector(
                    "capture",
                    "Capture",
                    "Photo,Photography,Aperture,Gallery,Images",
                    "art",
                    "Art",
                    R.drawable.hc_ic_hcicaperture
                ),
                HCImageVector(
                    "book_headphones",
                    "Book Headphones",
                    "Audiobook,Listening,Reading,Headphones,Novel",
                    "art",
                    "Art",
                    R.drawable.hc_ic_book_headphones
                ),
                HCImageVector(
                    "disc_3",
                    "Disc 3",
                    "Music,CD,Album,Audio,Playback",
                    "art",
                    "Art",
                    R.drawable.hc_ic_disc_3
                ),
                HCImageVector(
                    "music_4",
                    "Music 4",
                    "Melody,Song,Notes,Audio,Play",
                    "art",
                    "Art",
                    R.drawable.hc_ic_music_4
                ),
                HCImageVector(
                    "book_image",
                    "Book Image",
                    "Photo,Album,Scrapbook,Reading,Memories",
                    "art",
                    "Art",
                    R.drawable.hc_ic_book_image
                ),
                HCImageVector(
                    "image_play",
                    "Image Play",
                    "Slideshow,Video,Gallery,Media,Playback",
                    "art",
                    "Art",
                    R.drawable.hc_ic_image_play
                ),
                HCImageVector(
                    "gift",
                    "Gift",
                    "Present,Surprise,Box,Celebration,Party",
                    "art",
                    "Art",
                    R.drawable.hc_ic_gift
                ),
                HCImageVector(
                    "blinds",
                    "Blinds",
                    "Window,Shade,Curtain,Interior,Design",
                    "art",
                    "Art",
                    R.drawable.hc_ic_blinds
                ),
                HCImageVector(
                    "blocks",
                    "Blocks",
                    "Cubes,Building,Toy,Stack,Play",
                    "art",
                    "Art",
                    R.drawable.hc_ic_blocks
                ),
                HCImageVector(
                    "bookmark",
                    "Bookmark",
                    "Reading,Page,Marker,Book,Save",
                    "art",
                    "Art",
                    R.drawable.hc_ic_bookmark
                ),
                HCImageVector(
                    "bookmark_check",
                    "Bookmark Check",
                    "Reading,Done,Marker,Book,Complete",
                    "art",
                    "Art",
                    R.drawable.hc_ic_bookmark_check
                ),
                HCImageVector(
                    "bookmark_plus",
                    "Bookmark Plus",
                    "Reading,Add,Marker,Book,Save",
                    "art",
                    "Art",
                    R.drawable.hc_ic_bookmark_plus
                ),
                HCImageVector(
                    "badge_info",
                    "Badge Info",
                    "Information,Details,Tag,Label,Help",
                    "art",
                    "Art",
                    R.drawable.hc_ic_badge_info
                ),
                HCImageVector(
                    "book_heart",
                    "Book Heart",
                    "Reading,Love,Novel,Favorite,Story",
                    "art",
                    "Art",
                    R.drawable.hc_ic_book_heart
                ),
                HCImageVector(
                    "book_key",
                    "Book Key",
                    "Reading,Secrets,Unlock,Knowledge,Story",
                    "art",
                    "Art",
                    R.drawable.hc_ic_book_key
                ),
                HCImageVector(
                    "open_book",
                    "Open Book",
                    "Reading,Study,Learning,Knowledge,Pages",
                    "art",
                    "Art",
                    R.drawable.hc_ic_open_book
                ),
                HCImageVector(
                    "book_marked",
                    "Book Marked",
                    "Reading,Bookmark,Page,Favorite,Save",
                    "art",
                    "Art",
                    R.drawable.hc_ic_book_marked
                ),
                HCImageVector(
                    "book_open_check",
                    "Book Open Check",
                    "Reading,Done,Complete,Study,Finished",
                    "art",
                    "Art",
                    R.drawable.hc_ic_book_open_check
                ),
                HCImageVector(
                    "book_plus",
                    "Book Plus",
                    "Reading,Add,Library,Collection,New",
                    "art",
                    "Art",
                    R.drawable.hc_ic_book_plus
                ),
                HCImageVector(
                    "boom_box",
                    "Boom Box",
                    "Music,Audio,Speaker,Play,Retro",
                    "art",
                    "Art",
                    R.drawable.hc_ic_boom_box
                ),
                HCImageVector(
                    "box",
                    "Box",
                    "Package,Gift,Container,Storage,Surprise",
                    "art",
                    "Art",
                    R.drawable.hc_ic_box
                ),
                HCImageVector(
                    "brain",
                    "Brain",
                    "Mind,Thinking,Intelligence,Knowledge,Creativity",
                    "art",
                    "Art",
                    R.drawable.hc_ic_brain
                ),
                HCImageVector(
                    "bci",
                    "Brain Computer Interface",
                    "Technology,Brain,Interface,Neuroscience,Innovation",
                    "art",
                    "Art",
                    R.drawable.hc_ic_brain_circuit
                ),
                HCImageVector(
                    "brain_cog",
                    "Brain Cog",
                    "Mind,Thinking,Gear,Knowledge,Process",
                    "art",
                    "Art",
                    R.drawable.hc_ic_brain_cog
                ),
                HCImageVector(
                    "cake",
                    "Cake",
                    "Dessert,Birthday,Celebration,Sweet,Baking",
                    "art",
                    "Art",
                    R.drawable.hc_ic_cake
                ),
                HCImageVector(
                    "cake_slice",
                    "Cake Slice",
                    "Dessert,Birthday,Sweet,Snack,Portion",
                    "art",
                    "Art",
                    R.drawable.hc_ic_cake_slice
                ),
                HCImageVector(
                    "church",
                    "Church",
                    "Religion,Building,Faith,Prayer,Worship",
                    "art",
                    "Art",
                    R.drawable.hc_ic_church
                ),
                HCImageVector(
                    "circle",
                    "Circle",
                    "Shape,Geometry,Round,Design,Art",
                    "art",
                    "Art",
                    R.drawable.hc_ic_circle
                ),
                HCImageVector(
                    "circuit_board",
                    "Circuit Board",
                    "Electronics,Technology,Hardware,Chip,Engineering",
                    "art",
                    "Art",
                    R.drawable.hc_ic_circuit_board
                ),
                HCImageVector(
                    "clapperboard",
                    "Clapperboard",
                    "Film,Movie,Director,Cinema,Action",
                    "art",
                    "Art",
                    R.drawable.hc_ic_clapperboard
                ),
                HCImageVector(
                    "clipboard_check",
                    "Clipboard Check",
                    "List,Done,Task,Complete,Checklist",
                    "art",
                    "Art",
                    R.drawable.hc_ic_clipboard_check
                ),
                HCImageVector(
                    "codepen",
                    "Codepen",
                    "Coding,Development,Platform,Design,Web",
                    "art",
                    "Art",
                    R.drawable.hc_ic_codepen
                ),
                HCImageVector(
                    "combine",
                    "Combine",
                    "Merge,Mix,Blend,Join,Unite",
                    "art",
                    "Art",
                    R.drawable.hc_ic_combine
                ),
                HCImageVector(
                    "dices",
                    "Dices",
                    "Games,Gambling,Cubes,Roll,Sides",
                    "art",
                    "Art",
                    R.drawable.hc_ic_dices
                ),
                HCImageVector(
                    "dice_5",
                    "Dice 5",
                    "Games,Gambling,Cube,Roll,Number",
                    "art",
                    "Art",
                    R.drawable.hc_ic_dice_5
                ),
                HCImageVector(
                    "dot",
                    "Dot",
                    "Point,Shape,Mark,Circle,Design",
                    "art",
                    "Art",
                    R.drawable.hc_ic_dot
                ),
                HCImageVector(
                    "drafting_compass",
                    "Drafting Compass",
                    "Drawing,Design,Geometry,Tool,Art",
                    "art",
                    "Art",
                    R.drawable.hc_ic_drafting_compass
                ),
                HCImageVector(
                    "drum",
                    "Drum",
                    "Music,Instrument,Beat,Rhythm,Play",
                    "art",
                    "Art",
                    R.drawable.hc_ic_drum
                ),
                HCImageVector(
                    "ferris_wheel",
                    "Ferris Wheel",
                    "Amusement,Ride,Fair,Carnival,Fun",
                    "art",
                    "Art",
                    R.drawable.hc_ic_ferris_wheel
                ),
                HCImageVector(
                    "file_audio",
                    "File Audio",
                    "Music,Sound,Audio,Track,Recording",
                    "art",
                    "Art",
                    R.drawable.hc_ic_file_audio
                ),
                HCImageVector(
                    "file_chart_line",
                    "File Chart Line",
                    "Graph,Data,Analysis,Trends,Statistics",
                    "art",
                    "Art",
                    R.drawable.hc_ic_file_chart_line
                ),
                HCImageVector(
                    "file_chart_pie",
                    "File Chart Pie",
                    "Graph,Data,Analysis,Pie,Statistics",
                    "art",
                    "Art",
                    R.drawable.hc_ic_file_chart_pie
                ),
                HCImageVector(
                    "file_check",
                    "File Check",
                    "Document,Done,Complete,Verify,Approval",
                    "art",
                    "Art",
                    R.drawable.hc_ic_file_check
                ),
                HCImageVector(
                    "file_code_2",
                    "File Code 2",
                    "Programming,Code,Development,Script,Tech",
                    "art",
                    "Art",
                    R.drawable.hc_ic_file_code_2
                ),
                HCImageVector(
                    "file_image",
                    "File Image",
                    "Photo,Picture,Gallery,Media,Visual",
                    "art",
                    "Art",
                    R.drawable.hc_ic_file_image
                ),
                HCImageVector(
                    "file_json",
                    "File Json",
                    "Data,Code,Format,Programming,Script",
                    "art",
                    "Art",
                    R.drawable.hc_ic_file_json
                ),
                HCImageVector(
                    "file_music",
                    "File Music",
                    "Audio,Song,Track,Media,Play",
                    "art",
                    "Art",
                    R.drawable.hc_ic_file_music
                ),
                HCImageVector(
                    "file_video",
                    "File Video",
                    "Movie,Clip,Media,Playback,Recording",
                    "art",
                    "Art",
                    R.drawable.hc_ic_file_video
                ),
                HCImageVector(
                    "film",
                    "Film",
                    "Movie,Cinema,Video,Reel,Director",
                    "art",
                    "Art",
                    R.drawable.hc_ic_film
                ),
                HCImageVector(
                    "gamepad_2",
                    "Gamepad 2",
                    "Gaming,Controller,Play,Joystick,Entertainment",
                    "art",
                    "Art",
                    R.drawable.hc_ic_gamepad_2
                ),
                HCImageVector(
                    "hand_heart",
                    "Hand Heart",
                    "Love,Care,Support,Affection,Gesture",
                    "art",
                    "Art",
                    R.drawable.hc_ic_hand_heart
                ),
                HCImageVector(
                    "hand_helping",
                    "Hand Helping",
                    "Support,Assist,Aid,Charity,Gesture",
                    "art",
                    "Art",
                    R.drawable.hc_ic_hand_helping
                ),
                HCImageVector(
                    "hand_metal",
                    "Hand Metal",
                    "Rock,Gesture,Sign,Music,Expression",
                    "art",
                    "Art",
                    R.drawable.hc_ic_hand_metal
                ),
                HCImageVector(
                    "hcicalbum",
                    "Hcicalbum",
                    "Photos,Gallery,Memories,Album,Collection",
                    "art",
                    "Art",
                    R.drawable.hc_ic_hcicalbum
                ),
                HCImageVector(
                    "hcicaudiolines",
                    "Hcicaudiolines",
                    "Music,Sound,Audio,Frequency,Play",
                    "art",
                    "Art",
                    R.drawable.hc_ic_hcicaudiolines
                ),
                HCImageVector(
                    "hcicaudiowaveform",
                    "Hcicaudiowaveform",
                    "Music,Sound,Audio,Wave,Recording",
                    "art",
                    "Art",
                    R.drawable.hc_ic_hcicaudiowaveform
                ),
                HCImageVector(
                    "hcicbadgecheck",
                    "Hcicbadgecheck",
                    "Verified,Badge,Check,Approval,Success",
                    "art",
                    "Art",
                    R.drawable.hc_ic_hcicbadgecheck
                ),
                HCImageVector(
                    "keyboard_music",
                    "Keyboard Music",
                    "Music,Synth,Instrument,Play,Keys",
                    "art",
                    "Art",
                    R.drawable.hc_ic_keyboard_music
                ),
                HCImageVector(
                    "layers",
                    "Layers",
                    "Design,Art,Stack,Editing,Composition",
                    "art",
                    "Art",
                    R.drawable.hc_ic_layers
                ),
                HCImageVector(
                    "library_big",
                    "Library Big",
                    "Books,Reading,Knowledge,Study,Collection",
                    "art",
                    "Art",
                    R.drawable.hc_ic_library_big
                ),
                HCImageVector(
                    "lightbulb",
                    "Lightbulb",
                    "Idea,Creativity,Innovation,Thinking,Bright",
                    "art",
                    "Art",
                    R.drawable.hc_ic_lightbulb
                ),
                HCImageVector(
                    "loader_pinwheel",
                    "Loader Pinwheel",
                    "Loading,Spinner,Waiting,Progress,Animation",
                    "art",
                    "Art",
                    R.drawable.hc_ic_loader_pinwheel
                ),
                HCImageVector(
                    "monitor_play",
                    "Monitor Play",
                    "Video,Screen,Playback,Media,Watch",
                    "art",
                    "Art",
                    R.drawable.hc_ic_monitor_play
                ),
                HCImageVector(
                    "notebook",
                    "Notebook",
                    "Writing,Notes,Journal,Study,Sketch",
                    "art",
                    "Art",
                    R.drawable.hc_ic_notebook
                ),
                HCImageVector(
                    "paintbrush",
                    "Paintbrush",
                    "Art,Painting,Brush,Design,Creativity",
                    "art",
                    "Art",
                    R.drawable.hc_ic_paintbrush
                ),
                HCImageVector(
                    "paintbrush_vertical",
                    "Paintbrush Vertical",
                    "Art,Painting,Brush,Design,Vertical",
                    "art",
                    "Art",
                    R.drawable.hc_ic_paintbrush_vertical
                ),
                HCImageVector(
                    "piano",
                    "Piano",
                    "Music,Instrument,Keys,Play,Classical",
                    "art",
                    "Art",
                    R.drawable.hc_ic_piano
                ),
                HCImageVector(
                    "pyramid",
                    "Pyramid",
                    "Shape,Geometry,Structure,Art,Egypt",
                    "art",
                    "Art",
                    R.drawable.hc_ic_pyramid
                ),
                HCImageVector(
                    "sigma",
                    "Sigma",
                    "Math,Symbol,Greek,Science,Sum",
                    "art",
                    "Art",
                    R.drawable.hc_ic_sigma
                ),
                HCImageVector(
                    "signature",
                    "Signature",
                    "Sign,Autograph,Pen,Art,Unique",
                    "art",
                    "Art",
                    R.drawable.hc_ic_signature
                ),
                HCImageVector(
                    "spray_can",
                    "Spray Can",
                    "Graffiti,Art,Paint,Aerosol,Street",
                    "art",
                    "Art",
                    R.drawable.hc_ic_spray_can
                ),
                HCImageVector(
                    "video",
                    "Video",
                    "Movie,Clip,Media,Playback,Recording",
                    "art",
                    "Art",
                    R.drawable.hc_ic_video
                ),
                HCImageVector(
                    "view",
                    "View",
                    "Sight,Look,Observe,Eye,Perspective",
                    "art",
                    "Art",
                    R.drawable.hc_ic_view
                ),
            ),
            IconCategory.PRODUCTIVITY to listOf(
                HCImageVector(
                    "zap",
                    "Zap",
                    "Energy,Speed,Fast,Lightning,Power",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_zap
                ),
                HCImageVector(
                    "badge_dollar_sign",
                    "Badge Dollar Sign",
                    "Money,Currency,Finance,Badge,Payment",
                    "productivity",
                    "Art",
                    R.drawable.hc_ic_badge_dollar_sign
                ),
                HCImageVector(
                    "badge_euro",
                    "Badge Euro",
                    "Money,Currency,Finance,Badge,Payment",
                    "productivity",
                    "Art",
                    R.drawable.hc_ic_badge_euro
                ),
                HCImageVector(
                    "badge_indian_rupee",
                    "Badge Indian Rupee",
                    "Money,Currency,Finance,Badge,Payment",
                    "productivity",
                    "Art",
                    R.drawable.hc_ic_badge_indian_rupee
                ),
                HCImageVector(
                    "badge_japanese_yen",
                    "Badge Japanese Yen",
                    "Money,Currency,Finance,Badge,Payment",
                    "productivity",
                    "Art",
                    R.drawable.hc_ic_badge_japanese_yen
                ),
                HCImageVector(
                    "badge_pound_sterling",
                    "Badge Pound Sterling",
                    "Money,Currency,Finance,Badge,Payment",
                    "productivity",
                    "Art",
                    R.drawable.hc_ic_badge_pound_sterling
                ),
                HCImageVector(
                    "badge_russian_ruble",
                    "Badge Russian Ruble",
                    "Money,Currency,Finance,Badge,Payment",
                    "productivity",
                    "Art",
                    R.drawable.hc_ic_badge_russian_ruble
                ),
                HCImageVector(
                    "bitcoin",
                    "Bitcoin",
                    "Crypto,Currency,Finance,Blockchain,Payment",
                    "art",
                    "Art",
                    R.drawable.hc_ic_bitcoin
                ),
                HCImageVector(
                    "axe",
                    "Axe",
                    "Tool,Chop,Cut,Work,Blade",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_axe
                ),
                HCImageVector(
                    "badge_percent",
                    "Badge Percent",
                    "Discount,Finance,Badge,Rate,Sale",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_badge_percent
                ),
                HCImageVector(
                    "bell_dot",
                    "Bell Dot",
                    "Notification,Alert,Reminder,Signal,Notify",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_bell_dot
                ),
                HCImageVector(
                    "binary",
                    "Binary",
                    "Code,Data,Programming,Tech,Digital",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_binary
                ),
                HCImageVector(
                    "briefcase_business",
                    "Briefcase Business",
                    "Work,Office,Job,Business,Professional",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_briefcase_business
                ),
                HCImageVector(
                    "bug",
                    "Bug",
                    "Error,Debug,Software,Fix,Code",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_bug
                ),
                HCImageVector(
                    "calculator",
                    "Calculator",
                    "Math,Compute,Finance,Tool,Numbers",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_calculator
                ),
                HCImageVector(
                    "calendar_check",
                    "Calendar Check",
                    "Schedule,Event,Done,Plan,Date",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_calendar_check
                ),
                HCImageVector(
                    "calendar_clock",
                    "Calendar Clock",
                    "Schedule,Time,Event,Plan,Date",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_calendar_clock
                ),
                HCImageVector(
                    "calendar_days",
                    "Calendar Days",
                    "Schedule,Event,Plan,Date,Month",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_calendar_days
                ),
                HCImageVector(
                    "calendar_range",
                    "Calendar Range",
                    "Schedule,Event,Plan,Date,Period",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_calendar_range
                ),
                HCImageVector(
                    "case_upper",
                    "Case Upper",
                    "Text,Uppercase,Typing,Format,Edit",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_case_upper
                ),
                HCImageVector(
                    "chart_area",
                    "Chart Area",
                    "Graph,Data,Analysis,Trends,Statistics",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_chart_area
                ),
                HCImageVector(
                    "chart_column",
                    "Chart Column",
                    "Graph,Data,Analysis,Trends,Statistics",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_chart_column
                ),
                HCImageVector(
                    "chart_line",
                    "Chart Line",
                    "Graph,Data,Analysis,Trends,Statistics",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_chart_line
                ),
                HCImageVector(
                    "chart_network",
                    "Chart Network",
                    "Graph,Data,Analysis,Network,Connections",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_chart_network
                ),
                HCImageVector(
                    "chart_no_axes_combined",
                    "Chart No Axes Combined",
                    "Graph,Data,Analysis,Trends,Combined",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_chart_no_axes_combined
                ),
                HCImageVector(
                    "chart_pie",
                    "Chart Pie",
                    "Graph,Data,Analysis,Pie,Statistics",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_chart_pie
                ),
                HCImageVector(
                    "chart_spline",
                    "Chart Spline",
                    "Graph,Data,Analysis,Trends,Curve",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_chart_spline
                ),
                HCImageVector(
                    "clock",
                    "Clock",
                    "Time,Schedule,Timer,Watch,Hours",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_clock
                ),
                HCImageVector(
                    "contact",
                    "Contact",
                    "Person,Profile,Address,Info,People",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_contact
                ),
                HCImageVector(
                    "message",
                    "Message",
                    "Chat,Communication,Text,Talk,Conversation",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_message
                ),
                HCImageVector(
                    "file_terminal",
                    "File Terminal",
                    "Code,Terminal,Command,Script,Tech",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_file_terminal
                ),
                HCImageVector(
                    "flame_kindling",
                    "Flame Kindling",
                    "Fire,Energy,Start,Boost,Inspiration",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_flame_kindling
                ),
                HCImageVector(
                    "grip",
                    "Grip",
                    "Hold,Drag,Move,Handle,Control",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_grip
                ),
                HCImageVector(
                    "hammer",
                    "Hammer",
                    "Tool,Build,Fix,Work,Construction",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_hammer
                ),
                HCImageVector(
                    "hash",
                    "Hash",
                    "Tag,Code,Number,Symbol,Label",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_hash
                ),
                HCImageVector(
                    "hourglass",
                    "Hourglass",
                    "Time,Timer,Wait,Duration,Sand",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_hourglass
                ),
                HCImageVector(
                    "lamp",
                    "Lamp",
                    "Light,Study,Work,Desk,Bright",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_lamp
                ),
                HCImageVector(
                    "lamp_desk",
                    "Lamp Desk",
                    "Light,Study,Work,Desk,Bright",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_lamp_desk
                ),
                HCImageVector(
                    "layout_dashboard",
                    "Layout Dashboard",
                    "Dashboard,View,Interface,Data,Overview",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_layout_dashboard
                ),
                HCImageVector(
                    "layout_list",
                    "Layout List",
                    "List,View,Interface,Tasks,Items",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_layout_list
                ),
                HCImageVector(
                    "list_todo",
                    "List Todo",
                    "Tasks,Checklist,Plan,Work,Items",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_list_todo
                ),
                HCImageVector(
                    "mail",
                    "Mail",
                    "Email,Message,Communication,Inbox,Send",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_mail
                ),
                HCImageVector(
                    "mail_check",
                    "Mail Check",
                    "Email,Message,Done,Inbox,Confirmed",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_mail_check
                ),
                HCImageVector(
                    "mail_search",
                    "Mail Search",
                    "Email,Message,Search,Inbox,Find",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_mail_search
                ),
                HCImageVector(
                    "memory_stick",
                    "Memory Stick",
                    "Storage,USB,Data,Drive,Tech",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_memory_stick
                ),
                HCImageVector(
                    "mouse",
                    "Mouse",
                    "Computer,Cursor,Click,Device,Tech",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_mouse
                ),
                HCImageVector(
                    "newspaper",
                    "Newspaper",
                    "News,Reading,Article,Journal,Print",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_newspaper
                ),
                HCImageVector(
                    "origami",
                    "Origami",
                    "Paper,Fold,Craft,Art,Design",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_origami
                ),
                HCImageVector(
                    "paperclip",
                    "Paperclip",
                    "Attach,Clip,Document,File,Link",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_paperclip
                ),
                HCImageVector(
                    "percent",
                    "Percent",
                    "Discount,Rate,Finance,Math,Sale",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_percent
                ),
                HCImageVector(
                    "pickaxe",
                    "Pickaxe",
                    "Tool,Mining,Dig,Work,Construction",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_pickaxe
                ),
                HCImageVector(
                    "piggy_bank",
                    "Piggy Bank",
                    "Savings,Money,Finance,Budget,Coin",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_piggy_bank
                ),
                HCImageVector(
                    "plug",
                    "Plug",
                    "Power,Charge,Connect,Electric,Device",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_plug
                ),
                HCImageVector(
                    "plug_zap",
                    "Plug Zap",
                    "Power,Charge,Connect,Electric,Fast",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_plug_zap
                ),
                HCImageVector(
                    "pocket_knife",
                    "Pocket Knife",
                    "Tool,Blade,Utility,Outdoor,Cut",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_pocket_knife
                ),
                HCImageVector(
                    "presentation",
                    "Presentation",
                    "Slides,Talk,Meeting,Speech,Work",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_presentation
                ),
                HCImageVector(
                    "printer",
                    "Printer",
                    "Print,Document,Office,Device,Paper",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_printer
                ),
                HCImageVector(
                    "projector",
                    "Projector",
                    "Presentation,Display,Screen,Device,Meeting",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_projector
                ),
                HCImageVector(
                    "puzzle",
                    "Puzzle",
                    "Challenge,Game,Piece,Solve,Thinking",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_puzzle
                ),
                HCImageVector(
                    "quote",
                    "Quote",
                    "Text,Speech,Words,Inspiration,Message",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_quote
                ),
                HCImageVector(
                    "rocket",
                    "Rocket",
                    "Launch,Start,Speed,Innovation,Project",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_rocket
                ),
                HCImageVector(
                    "router",
                    "Router",
                    "Network,Internet,Device,Connectivity,Tech",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_router
                ),
                HCImageVector(
                    "rows_4",
                    "Rows 4",
                    "Layout,List,Rows,Table,Organize",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_rows_4
                ),
                HCImageVector(
                    "satellite",
                    "Satellite",
                    "Space,Communication,Orbit,Tech,Signal",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_satellite
                ),
                HCImageVector(
                    "save",
                    "Save",
                    "Store,Backup,File,Data,Keep",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_save
                ),
                HCImageVector(
                    "scale",
                    "Scale",
                    "Balance,Measure,Justice,Law,Weight",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_scale
                ),
                HCImageVector(
                    "scan_eye",
                    "Scan Eye",
                    "Vision,Scan,Detect,Security,Tech",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_scan_eye
                ),
                HCImageVector(
                    "scan_face",
                    "Scan Face",
                    "Face,Scan,Detect,Security,Tech",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_scan_face
                ),
                HCImageVector(
                    "scan_qr_code",
                    "Scan Qr Code",
                    "QR,Scan,Code,Tech,Link",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_scan_qr_code
                ),
                HCImageVector(
                    "school",
                    "School",
                    "Education,Learning,Building,Study,Class",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_school
                ),
                HCImageVector(
                    "screen_share",
                    "Screen Share",
                    "Share,Display,Screen,Meeting,Tech",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_screen_share
                ),
                HCImageVector(
                    "scroll_text",
                    "Scroll Text",
                    "Document,Text,Scroll,Paper,Read",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_scroll_text
                ),
                HCImageVector(
                    "search_check",
                    "Search Check",
                    "Find,Done,Search,Verify,Complete",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_search_check
                ),
                HCImageVector(
                    "search_code",
                    "Search Code",
                    "Find,Code,Programming,Search,Tech",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_search_code
                ),
                HCImageVector(
                    "server_crash",
                    "Server Crash",
                    "Error,Server,Tech,Failure,Network",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_server_crash
                ),
                HCImageVector(
                    "shield_check",
                    "Shield Check",
                    "Security,Protect,Verified,Safe,Done",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_shield_check
                ),
                HCImageVector(
                    "square_asterisk",
                    "Square Asterisk",
                    "Symbol,Mark,Star,Box,Highlight",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_square_asterisk
                ),
                HCImageVector(
                    "square_bottom_dashed_scissors",
                    "Square Bottom Dashed Scissors",
                    "Cut,Scissors,Dashed,Box,Edit",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_square_bottom_dashed_scissors
                ),
                HCImageVector(
                    "square_chart_gantt",
                    "Square Chart Gantt",
                    "Gantt,Chart,Plan,Timeline,Project",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_square_chart_gantt
                ),
                HCImageVector(
                    "square_m",
                    "Square M",
                    "Symbol,Box,Mark,Letter,Design",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_square_m
                ),
                HCImageVector(
                    "square_terminal",
                    "Square Terminal",
                    "Code,Terminal,Command,Script,Tech",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_square_terminal
                ),
                HCImageVector(
                    "swatch_book",
                    "Swatch Book",
                    "Colors,Design,Palette,Book,Art",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_swatch_book
                ),
                HCImageVector(
                    "tally_4",
                    "Tally 4",
                    "Count,Mark,Tally,Score,Number",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_tally_4
                ),
                HCImageVector(
                    "tally_5",
                    "Tally 5",
                    "Count,Mark,Tally,Score,Number",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_tally_5
                ),
                HCImageVector(
                    "target",
                    "Target",
                    "Goal,Focus,Aim,Objective,Plan",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_target
                ),
                HCImageVector(
                    "terminal",
                    "Terminal",
                    "Code,Command,Script,Tech,Console",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_terminal
                ),
                HCImageVector(
                    "text_quote",
                    "Text Quote",
                    "Quote,Text,Speech,Words,Message",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_text_quote
                ),
                HCImageVector(
                    "text_search",
                    "Text Search",
                    "Find,Search,Text,Words,Query",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_text_search
                ),
                HCImageVector(
                    "trash_2",
                    "Trash 2",
                    "Delete,Remove,Bin,Garbage,Clear",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_trash_2
                ),
                HCImageVector(
                    "trending_down",
                    "Trending Down",
                    "Decline,Graph,Trend,Decrease,Stats",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_trending_down
                ),
                HCImageVector(
                    "trending_up",
                    "Trending Up",
                    "Growth,Graph,Trend,Increase,Stats",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_trending_up
                ),
                HCImageVector(
                    "university",
                    "University",
                    "Education,Learning,School,Study,Campus",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_university
                ),
                HCImageVector(
                    "wallet_cards",
                    "Wallet Cards",
                    "Money,Payment,Cards,Finance,Wallet",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_wallet_cards
                ),
                HCImageVector(
                    "washing_machine",
                    "Washing Machine",
                    "Clean,Laundry,Appliance,Housework,Chore",
                    "productivity",
                    "Productivity",
                    R.drawable.hc_ic_washing_machine
                ),
            ),
            IconCategory.NATURE to listOf(
                HCImageVector(
                    "plant",
                    "Plant",
                    "Nature,Growth,Leaf,Garden,Flora",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_plant
                ),
                HCImageVector(
                    "cloud_drizzle",
                    "Cloud Drizzle",
                    "Weather,Rain,Drizzle,Cloud,Moisture",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_cloud_drizzle
                ),
                HCImageVector(
                    "cat",
                    "Cat",
                    "Animal,Pet,Feline,Purry,Kitty",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_cat
                ),
                HCImageVector(
                    "dog",
                    "Dog",
                    "Animal,Pet,Canine,Bark,Puppy",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_dog
                ),
                HCImageVector(
                    "fish",
                    "Fish",
                    "Animal,Sea,Ocean,Swim,Aquatic",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_fish
                ),
                HCImageVector(
                    "fish_symbol",
                    "Fish Symbol",
                    "Sea,Ocean,Fish,Symbol,Aquatic",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_fish_symbol
                ),
                HCImageVector(
                    "flower_2",
                    "Flower 2",
                    "Nature,Blossom,Petals,Garden,Flora",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_flower_2
                ),
                HCImageVector(
                    "leaf",
                    "Leaf",
                    "Nature,Plant,Green,Foliage,Tree",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_leaf
                ),
                HCImageVector(
                    "mountain_snow",
                    "Mountain Snow",
                    "Nature,Peak,Snow,Mountain,Winter",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_mountain_snow
                ),
                HCImageVector(
                    "paw_print",
                    "Paw Print",
                    "Animal,Track,Footprint,Pet,Nature",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_paw_print
                ),
                HCImageVector(
                    "rabbit",
                    "Rabbit",
                    "Animal,Bunny,Pet,Hop,Nature",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_rabbit
                ),
                HCImageVector(
                    "sailboat",
                    "Sailboat",
                    "Sea,Boat,Sail,Ocean,Nature",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_sailboat
                ),
                HCImageVector(
                    "ship",
                    "Ship",
                    "Sea,Boat,Ocean,Travel,Nature",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_ship
                ),
                HCImageVector(
                    "snail",
                    "Snail",
                    "Animal,Slow,Shell,Nature,Crawl",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_snail
                ),
                HCImageVector(
                    "sprout",
                    "Sprout",
                    "Nature,Growth,Plant,Seedling,Flora",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_sprout
                ),
                HCImageVector(
                    "squirrel",
                    "Squirrel",
                    "Animal,Rodent,Nature,Forest,Tail",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_squirrel
                ),
                HCImageVector(
                    "sun",
                    "Sun",
                    "Weather,Light,Bright,Day,Nature",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_sun
                ),
                HCImageVector(
                    "sunrise",
                    "Sunrise",
                    "Weather,Dawn,Morning,Sun,Nature",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_sunrise
                ),
                HCImageVector(
                    "sunset",
                    "Sunset",
                    "Weather,Dusk,Evening,Sun,Nature",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_sunset
                ),
                HCImageVector(
                    "sun_moon",
                    "Sun Moon",
                    "Weather,Day,Night,Sun,Moon",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_sun_moon
                ),
                HCImageVector(
                    "tent_tree",
                    "Tent Tree",
                    "Nature,Camping,Forest,Tent,Outdoor",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_tent_tree
                ),
                HCImageVector(
                    "tree_deciduous",
                    "Tree Deciduous",
                    "Nature,Tree,Leaf,Forest,Plant",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_tree_deciduous
                ),
                HCImageVector(
                    "tree_palm",
                    "Tree Palm",
                    "Nature,Tree,Tropical,Beach,Plant",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_tree_palm
                ),
                HCImageVector(
                    "tree_pine",
                    "Tree Pine",
                    "Nature,Tree,Forest,Evergreen,Plant",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_tree_pine
                ),
                HCImageVector(
                    "turtle",
                    "Turtle",
                    "Animal,Reptile,Sea,Slow,Nature",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_turtle
                ),
                HCImageVector(
                    "worm",
                    "Worm",
                    "Animal,Insect,Nature,Soil,Crawl",
                    "nature",
                    "Nature",
                    R.drawable.hc_ic_worm
                ),
            ),
            IconCategory.HEALTH to listOf(
                HCImageVector(
                    "walk",
                    "Walk",
                    "Exercise,Health,Step,Fitness,Stroll",
                    "health",
                    "Health",
                    R.drawable.hc_ic_walk
                ),
                HCImageVector(
                    "stethoscope",
                    "Stethoscope",
                    "Doctor,Health,Medical,Checkup,Tool",
                    "health",
                    "Health",
                    R.drawable.hc_ic_stethoscope
                ),
                HCImageVector(
                    "apple",
                    "Apple",
                    "Fruit,Health,Food,Nutrition,Diet",
                    "health",
                    "Health",
                    R.drawable.hc_ic_apple
                ),
                HCImageVector(
                    "bed",
                    "Bed",
                    "Sleep,Rest,Health,Relax,Bedroom",
                    "health",
                    "Health",
                    R.drawable.hc_ic_bed
                ),
                HCImageVector(
                    "moisturizer",
                    "Moisturizer",
                    "Skincare,Cream,Health,Lotion,Hydration",
                    "health",
                    "Health",
                    R.drawable.hc_ic_moisturizer
                ),
                HCImageVector(
                    "activity",
                    "Activity",
                    "Exercise,Fitness,Health,Workout,Active",
                    "health",
                    "Health",
                    R.drawable.hc_ic_activity
                ),
                HCImageVector(
                    "alarm_smoke",
                    "Alarm Smoke",
                    "Safety,Health,Alarm,Smoke,Alert",
                    "health",
                    "Health",
                    R.drawable.hc_ic_alarm_smoke
                ),
                HCImageVector(
                    "accessibility",
                    "Accessibility",
                    "Health,Support,Disability,Access,Inclusion",
                    "health",
                    "Health",
                    R.drawable.hc_ic_accessibility
                ),
                HCImageVector(
                    "ambulance",
                    "Ambulance",
                    "Health,Medical,Emergency,Vehicle,Hospital",
                    "health",
                    "Health",
                    R.drawable.hc_ic_ambulance
                ),
                HCImageVector(
                    "banana",
                    "Banana",
                    "Fruit,Health,Food,Nutrition,Diet",
                    "health",
                    "Health",
                    R.drawable.hc_ic_banana
                ),
                HCImageVector(
                    "bean",
                    "Bean",
                    "Food,Health,Nutrition,Protein,Diet",
                    "health",
                    "Health",
                    R.drawable.hc_ic_bean
                ),
                HCImageVector(
                    "beer_off",
                    "Beer Off",
                    "Health,Alcohol,No,Drink,Abstinence",
                    "health",
                    "Health",
                    R.drawable.hc_ic_beer_off
                ),
                HCImageVector(
                    "biceps_flexed",
                    "Biceps Flexed",
                    "Fitness,Health,Strength,Exercise,Muscle",
                    "health",
                    "Health",
                    R.drawable.hc_ic_biceps_flexed
                ),
                HCImageVector(
                    "bone",
                    "Bone",
                    "Health,Anatomy,Skeleton,Strength,Body",
                    "health",
                    "Health",
                    R.drawable.hc_ic_bone
                ),
                HCImageVector(
                    "briefcase_medical",
                    "Briefcase Medical",
                    "Health,Doctor,Medical,Kit,Emergency",
                    "health",
                    "Health",
                    R.drawable.hc_ic_briefcase_medical
                ),
                HCImageVector(
                    "candy_off",
                    "Candy Off",
                    "Health,No,Sweets,Diet,Abstinence",
                    "health",
                    "Health",
                    R.drawable.hc_ic_candy_off
                ),
                HCImageVector(
                    "carrot",
                    "Carrot",
                    "Vegetable,Health,Food,Nutrition,Diet",
                    "health",
                    "Health",
                    R.drawable.hc_ic_carrot
                ),
                HCImageVector(
                    "cherry",
                    "Cherry",
                    "Fruit,Health,Food,Nutrition,Diet",
                    "health",
                    "Health",
                    R.drawable.hc_ic_cherry
                ),
                HCImageVector(
                    "cigarette_off",
                    "Cigarette Off",
                    "Health,No,Smoking,Abstinence,Quit",
                    "health",
                    "Health",
                    R.drawable.hc_ic_cigarette_off
                ),
                HCImageVector(
                    "citrus",
                    "Citrus",
                    "Fruit,Health,Food,Nutrition,Orange",
                    "health",
                    "Health",
                    R.drawable.hc_ic_citrus
                ),
                HCImageVector(
                    "coffee",
                    "Coffee",
                    "Drink,Health,Caffeine,Morning,Beverage",
                    "health",
                    "Health",
                    R.drawable.hc_ic_coffee
                ),
                HCImageVector(
                    "cookie",
                    "Cookie",
                    "Snack,Health,Food,Sweet,Biscuit",
                    "health",
                    "Health",
                    R.drawable.hc_ic_cookie
                ),
                HCImageVector(
                    "croissant",
                    "Croissant",
                    "Food,Health,Breakfast,Pastry,Bread",
                    "health",
                    "Health",
                    R.drawable.hc_ic_croissant
                ),
                HCImageVector(
                    "cup_soda",
                    "Cup Soda",
                    "Drink,Health,Soda,Beverage,Refreshment",
                    "health",
                    "Health",
                    R.drawable.hc_ic_cup_soda
                ),
                HCImageVector(
                    "dessert",
                    "Dessert",
                    "Sweets,Health,Food,Dessert,Treat",
                    "health",
                    "Health",
                    R.drawable.hc_ic_dessert
                ),
                HCImageVector(
                    "dna",
                    "Dna",
                    "Health,Genetics,Biology,Science,Life",
                    "health",
                    "Health",
                    R.drawable.hc_ic_dna
                ),
                HCImageVector(
                    "donut",
                    "Donut",
                    "Sweets,Health,Food,Dessert,Treat",
                    "health",
                    "Health",
                    R.drawable.hc_ic_donut
                ),
                HCImageVector(
                    "droplet",
                    "Droplet",
                    "Water,Health,Hydration,Drop,Liquid",
                    "health",
                    "Health",
                    R.drawable.hc_ic_droplet
                ),
                HCImageVector(
                    "egg",
                    "Egg",
                    "Food,Health,Nutrition,Protein,Breakfast",
                    "health",
                    "Health",
                    R.drawable.hc_ic_egg
                ),
                HCImageVector(
                    "eye",
                    "Eye",
                    "Vision,Health,Sight,Look,Body",
                    "health",
                    "Health",
                    R.drawable.hc_ic_eye
                ),
                HCImageVector(
                    "eye_closed",
                    "Eye Closed",
                    "Sleep,Rest,Health,Eye,Relax",
                    "health",
                    "Health",
                    R.drawable.hc_ic_eye_closed
                ),
                HCImageVector(
                    "glass_water",
                    "Glass Water",
                    "Water,Health,Hydration,Drink,Glass",
                    "health",
                    "Health",
                    R.drawable.hc_ic_glass_water
                ),
                HCImageVector(
                    "grape",
                    "Grape",
                    "Fruit,Health,Food,Nutrition,Diet",
                    "health",
                    "Health",
                    R.drawable.hc_ic_grape
                ),
                HCImageVector(
                    "hand_heart",
                    "Hand Heart",
                    "Love,Care,Health,Support,Gesture",
                    "health",
                    "Health",
                    R.drawable.hc_ic_hand_heart
                ),
                HCImageVector(
                    "heart_filled",
                    "Heart Filled",
                    "Health,Love,Care,Heart,Emotion",
                    "health",
                    "Health",
                    R.drawable.hc_ic_heart_filled
                ),
                HCImageVector(
                    "heart_pulse",
                    "Heart Pulse",
                    "Health,Heartbeat,Fitness,Monitor,Vital",
                    "health",
                    "Health",
                    R.drawable.hc_ic_heart_pulse
                ),
                HCImageVector(
                    "heater",
                    "Heater",
                    "Warmth,Health,Device,Heat,Comfort",
                    "health",
                    "Health",
                    R.drawable.hc_ic_heater
                ),
                HCImageVector(
                    "hospital",
                    "Hospital",
                    "Health,Medical,Care,Building,Emergency",
                    "health",
                    "Health",
                    R.drawable.hc_ic_hospital
                ),
                HCImageVector(
                    "ice_cream_bowl",
                    "Ice Cream Bowl",
                    "Dessert,Health,Sweets,Treat,Cold",
                    "health",
                    "Health",
                    R.drawable.hc_ic_ice_cream_bowl
                ),
                HCImageVector(
                    "ice_cream_cone",
                    "Ice Cream Cone",
                    "Dessert,Health,Sweets,Treat,Cold",
                    "health",
                    "Health",
                    R.drawable.hc_ic_ice_cream_cone
                ),
                HCImageVector(
                    "leafy_green",
                    "Leafy Green",
                    "Vegetable,Health,Nutrition,Diet,Salad",
                    "health",
                    "Health",
                    R.drawable.hc_ic_leafy_green
                ),
                HCImageVector(
                    "microscope",
                    "Microscope",
                    "Health,Science,Research,Lab,Medical",
                    "health",
                    "Health",
                    R.drawable.hc_ic_microscope
                ),
                HCImageVector(
                    "microwave",
                    "Microwave",
                    "Cooking,Health,Appliance,Kitchen,Heat",
                    "health",
                    "Health",
                    R.drawable.hc_ic_microwave
                ),
                HCImageVector(
                    "milk",
                    "Milk",
                    "Drink,Health,Nutrition,Dairy,Food",
                    "health",
                    "Health",
                    R.drawable.hc_ic_milk
                ),
                HCImageVector(
                    "milk_off",
                    "Milk Off",
                    "Health,No,Dairy,Drink,Abstinence",
                    "health",
                    "Health",
                    R.drawable.hc_ic_milk_off
                ),
                HCImageVector(
                    "nut",
                    "Nut",
                    "Food,Health,Nutrition,Snack,Protein",
                    "health",
                    "Health",
                    R.drawable.hc_ic_nut
                ),
                HCImageVector(
                    "nut_off",
                    "Nut Off",
                    "Health,No,Allergy,Diet,Abstinence",
                    "health",
                    "Health",
                    R.drawable.hc_ic_nut_off
                ),
                HCImageVector(
                    "person_standing",
                    "Person Standing",
                    "Health,Body,Posture,Fitness,Stand",
                    "health",
                    "Health",
                    R.drawable.hc_ic_person_standing
                ),
                HCImageVector(
                    "pill",
                    "Pill",
                    "Health,Medicine,Medical,Supplement,Drug",
                    "health",
                    "Health",
                    R.drawable.hc_ic_pill
                ),
                HCImageVector(
                    "pipette",
                    "Pipette",
                    "Health,Science,Lab,Medical,Dropper",
                    "health",
                    "Health",
                    R.drawable.hc_ic_pipette
                ),
                HCImageVector(
                    "pizza",
                    "Pizza",
                    "Food,Health,Meal,Snack,Italian",
                    "health",
                    "Health",
                    R.drawable.hc_ic_pizza
                ),
                HCImageVector(
                    "popcorn",
                    "Popcorn",
                    "Snack,Health,Food,Treat,Movie",
                    "health",
                    "Health",
                    R.drawable.hc_ic_popcorn
                ),
                HCImageVector(
                    "popsicle",
                    "Popsicle",
                    "Dessert,Health,Sweets,Treat,Cold",
                    "health",
                    "Health",
                    R.drawable.hc_ic_popsicle
                ),
                HCImageVector(
                    "recycle",
                    "Recycle",
                    "Health,Environment,Sustainability,Reuse,Cycle",
                    "health",
                    "Health",
                    R.drawable.hc_ic_recycle
                ),
                HCImageVector(
                    "ribbon",
                    "Ribbon",
                    "Health,Awareness,Support,Cause,Ribbon",
                    "health",
                    "Health",
                    R.drawable.hc_ic_ribbon
                ),
                HCImageVector(
                    "salad",
                    "Salad",
                    "Food,Health,Nutrition,Diet,Vegetable",
                    "health",
                    "Health",
                    R.drawable.hc_ic_salad
                ),
                HCImageVector(
                    "shield_plus",
                    "Shield Plus",
                    "Health,Protect,Medical,Safety,Add",
                    "health",
                    "Health",
                    R.drawable.hc_ic_shield_plus
                ),
                HCImageVector(
                    "shower_head",
                    "Shower Head",
                    "Hygiene,Health,Bath,Shower,Clean",
                    "health",
                    "Health",
                    R.drawable.hc_ic_shower_head
                ),
                HCImageVector(
                    "soup",
                    "Soup",
                    "Food,Health,Nutrition,Meal,Warm",
                    "health",
                    "Health",
                    R.drawable.hc_ic_soup
                ),
                HCImageVector(
                    "square_activity",
                    "Square Activity",
                    "Health,Fitness,Activity,Workout,Exercise",
                    "health",
                    "Health",
                    R.drawable.hc_ic_square_activity
                ),
                HCImageVector(
                    "syringe",
                    "Syringe",
                    "Health,Medical,Injection,Shot,Vaccine",
                    "health",
                    "Health",
                    R.drawable.hc_ic_syringe
                ),
                HCImageVector(
                    "test_tube_diagonal",
                    "Test Tube Diagonal",
                    "Health,Science,Lab,Medical,Research",
                    "health",
                    "Health",
                    R.drawable.hc_ic_test_tube_diagonal
                ),
                HCImageVector(
                    "thermometer",
                    "Thermometer",
                    "Health,Temperature,Medical,Fever,Measure",
                    "health",
                    "Health",
                    R.drawable.hc_ic_thermometer
                ),
                HCImageVector(
                    "user_check",
                    "User Check",
                    "Health,Profile,Verified,Person,Done",
                    "health",
                    "Health",
                    R.drawable.hc_ic_user_check
                ),
                HCImageVector(
                    "user_x",
                    "User X",
                    "Health,Profile,Remove,Person,Delete",
                    "health",
                    "Health",
                    R.drawable.hc_ic_user_x
                ),
                HCImageVector(
                    "utensils",
                    "Utensils",
                    "Food,Health,Eating,Kitchen,Dining",
                    "health",
                    "Health",
                    R.drawable.hc_ic_utensils
                ),
                HCImageVector(
                    "utensils_crossed",
                    "Utensils Crossed",
                    "Food,Health,Eating,Kitchen,Dining",
                    "health",
                    "Health",
                    R.drawable.hc_ic_utensils_crossed
                ),
                HCImageVector(
                    "vegan",
                    "Vegan",
                    "Health,Diet,Food,Plantbased,Nutrition",
                    "health",
                    "Health",
                    R.drawable.hc_ic_vegan
                ),
                HCImageVector(
                    "wheat",
                    "Wheat",
                    "Food,Health,Nutrition,Grain,Diet",
                    "health",
                    "Health",
                    R.drawable.hc_ic_wheat
                ),
                HCImageVector(
                    "wine_off",
                    "Wine Off",
                    "Health,No,Alcohol,Drink,Abstinence",
                    "health",
                    "Health",
                    R.drawable.hc_ic_wine_off
                ),
            ),
            IconCategory.SOCIAL to listOf(
                HCImageVector(
                    "earth",
                    "Earth, Mars, Proxima B",
                    "Planet,Space,World,Globe,Nature",
                    "social",
                    "Social",
                    R.drawable.hc_ic_earth
                ),
                HCImageVector(
                    "globe",
                    "Globe",
                    "World,Planet,Map,Global,Travel",
                    "social",
                    "Social",
                    R.drawable.hc_ic_globe
                ),
                HCImageVector(
                    "twitter_x",
                    "Twitter X",
                    "Social,Media,Platform,Tweet,Chat",
                    "social",
                    "Social",
                    R.drawable.hc_ic_twitter_x
                ),
                HCImageVector(
                    "twitter",
                    "Twitter",
                    "Social,Media,Platform,Tweet,Chat",
                    "social",
                    "Social",
                    R.drawable.hc_ic_twitter
                ),
                HCImageVector(
                    "bluesky",
                    "Bluesky",
                    "Social,Media,Platform,Chat,Network",
                    "social",
                    "Social",
                    R.drawable.hc_ic_bluesky
                ),
                HCImageVector(
                    "circle_fading_arrow_up",
                    "Circle Fading Arrow Up",
                    "Share,Upload,Arrow,Social,Send",
                    "social",
                    "Social",
                    R.drawable.hc_ic_circle_fading_arrow_up
                ),
                HCImageVector(
                    "instagram",
                    "Instagram",
                    "Social,Media,Platform,Photos,Share",
                    "social",
                    "Social",
                    R.drawable.hc_ic_instagram
                ),
                HCImageVector(
                    "facebook",
                    "Facebook",
                    "Social,Media,Platform,Friends,Share",
                    "social",
                    "Social",
                    R.drawable.hc_ic_facebook
                ),
                HCImageVector(
                    "linkedin",
                    "Linkedin",
                    "Social,Media,Professional,Network,Job",
                    "social",
                    "Social",
                    R.drawable.hc_ic_linkedin
                ),
                HCImageVector(
                    "dribbble",
                    "Dribbble",
                    "Social,Media,Design,Platform,Creative",
                    "social",
                    "Social",
                    R.drawable.hc_ic_dribbble
                ),
                HCImageVector(
                    "twitch",
                    "Twitch",
                    "Social,Media,Streaming,Platform,Gaming",
                    "social",
                    "Social",
                    R.drawable.hc_ic_twitch
                ),
                HCImageVector(
                    "female",
                    "Female",
                    "Gender,Woman,Person,Social,Symbol",
                    "social",
                    "Social",
                    R.drawable.hc_ic_hcicfemale
                ),
                HCImageVector(
                    "male",
                    "Male",
                    "Gender,Man,Person,Social,Symbol",
                    "social",
                    "Social",
                    R.drawable.hc_ic_hcicmale
                ),
                HCImageVector(
                    "map",
                    "Map",
                    "Location,Travel,Navigation,Places,Guide",
                    "social",
                    "Social",
                    R.drawable.hc_ic_map
                ),
                HCImageVector(
                    "network",
                    "Network",
                    "Connections,Social,Web,Links,Community",
                    "social",
                    "Social",
                    R.drawable.hc_ic_network
                ),
                HCImageVector(
                    "scan_heart",
                    "Scan Heart",
                    "Love,Scan,Detect,Social,Emotion",
                    "social",
                    "Social",
                    R.drawable.hc_ic_scan_heart
                ),
                HCImageVector(
                    "train_front",
                    "Train Front",
                    "Travel,Transport,Train,Commute,Journey",
                    "social",
                    "Social",
                    R.drawable.hc_ic_train_front
                ),
                HCImageVector(
                    "wand",
                    "Wand",
                    "Magic,Tool,Create,Social,Effect",
                    "social",
                    "Social",
                    R.drawable.hc_ic_wand
                ),
                HCImageVector(
                    "youtube",
                    "Youtube",
                    "Social,Media,Video,Platform,Streaming",
                    "social",
                    "Social",
                    R.drawable.hc_ic_youtube
                ),
            ),
            IconCategory.TRENDING to listOf(
                HCImageVector(
                    "grok",
                    "Grok",
                    "AI,Assistant,Trending,Tech,Helpful",
                    "trending",
                    "Trending",
                    R.drawable.hc_ic_grok
                )
            ),
        )
    }

    val allHabitIconList: List<HCImageVector> by lazy {
        iconsByCategory.values.flatten()
    }

    val hcIcPlus: HCImageVector = HCImageVector(
        id = "plus",
        name = "Plus",
        tags = "Add",
        categoryId = "habit_card",
        categoryName = "Habit Card",
        iconRes = R.drawable.hc_ic_plus
    )

    fun getIconsByCategory(category: IconCategory): List<HCImageVector> =
        iconsByCategory[category] ?: emptyList()
}